### PR TITLE
Add Panda firmware and dongle ID to offroad apk Developer menu

### PR DESCRIPTION
**Pull request by martinl**
This PR adds Panda firmware and dongle ID to offroad apk Developer menu, requires   https://github.com/commaai/openpilot/pull/695

org.gradle.jvmargs=-Xmx2048M resolves low memory warning when running ./build.sh

### CODE REVIEW

**Comment by eFiniLan** [comment]
awesome idea! would it be possible to make it clickable so it will then reflash panda?

**Comment by martinl** [comment]
Would Device menu be a better place for showing Panda info?

**Comment by martinl** [comment]
I rewrote https://github.com/commaai/openpilot/pull/695 to use boardd

**Comment by rbiasini** [comment]
@andyh2 @valish can we merge this PR? the openpilot side is already merged internally.

**Comment by andyh2** [comment]
The settings appear blank when panda disconnects because the params are removed (CLEAR_ON_PANDA_DISCONNECT param flag in the openpilot change). 
@martinl  Can you resolve the conflict and update this PR so the new rows in settings only appear when pandaFirmware/pandaDongleId are valid params? `typeof param === 'string'` is a reliable check.

**Comment by rbiasini** [comment]
Or maybe we show "NA" when params aren't valid. Either ways seems fine.

**Comment by andyh2** [comment]
Merged: https://github.com/commaai/openpilot-apks/commit/cb1094abbb9b4a858b8abcf56636859cd99d28e0

**Pull request closed without merging**
